apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: test-arm-images
  labels:
    "cross-platform-build": "enabled"
spec:
  nodeSelector:
    beta.kubernetes.io/arch: amd64
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.3.0
    args: ["--context=git://github.com/vijay-dcrust/simple-webhook.git",
            "--destination=851255665500.dkr.ecr.ap-southeast-1.amazonaws.com/db-central-repo:simple-webhook"
          ]
    env:
    - name: AWS_PROFILE
      value: sgcentral
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker/
    # when not using instance role
    - name: aws-secret
      mountPath: /root/.aws/  
  restartPolicy: Never
  volumes:
  - name: docker-config
    configMap:
      name: docker-config
  # when not using instance role
  - name: aws-secret
    secret:
      secretName: aws-secret
