apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-arm-pod
  name: test-arm-pod
spec:
  nodeSelector:
    "beta.kubernetes.io/arch": arm64
  containers:
  - image: 851255665500.dkr.ecr.ap-southeast-1.amazonaws.com/db-central-repo:simple-webhook-arm-cross-platform-generated
    name: test-arm-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: node.kubernets.io/arch
    value: arm64
status: {}
